// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Order struct {
	ID        string       `json:"id"`
	UserID    string       `json:"userId"`
	User      *User        `json:"user,omitempty"`
	Items     []*OrderItem `json:"items"`
	Total     float64      `json:"total"`
	Status    string       `json:"status"`
	CreatedAt string       `json:"createdAt"`
}

type OrderItem struct {
	ProductID string   `json:"productId"`
	Product   *Product `json:"product,omitempty"`
	Quantity  int      `json:"quantity"`
	Price     float64  `json:"price"`
}

type OrderItemInput struct {
	ProductID string `json:"productId"`
	Quantity  int    `json:"quantity"`
}

type Product struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	Stock       int     `json:"stock"`
}

type Query struct {
}

type User struct {
	ID     string   `json:"id"`
	Name   string   `json:"name"`
	Email  string   `json:"email"`
	Orders []*Order `json:"orders"`
}
